### ISSUE TITLE
SSG seems to be working with the url.searchParams()

### ISSUE THREAD

**Issue by psntr** [stephane-vanraes/sveltekit-sanity-starter#4]
Hi,

As the title suggests, I'm not able to use `export const prerender = true;` on my sitemap.xml page, as the log says:
`Error: Cannot access url.searchParams on a page with prerendering enabled at URL.get…`

any chance to make this works with some page set as prerender?

**Comment by stephane-vanraes** [comment]
The `searchParams` are used in two places in the template

1) in the handle hook where it checks for the "preview token"
2) in the /post/+page.server.ts load function where it used for pagination of the articles

Your sitemap should be outside of the scope of (2) so there shouldn't be a problem I suppose ?
For the handle hook there are two options basically

```diff
+ const isPreviewMode = !building && validatePreviewToken(event.url);
- const client = isPreviewMode ? previewClient : sanityClient;
```

(the `building` constant detects if you are building or prerendering [see docs](https://kit.svelte.dev/docs/modules#$app-environment-building)

Alternatively, you can use the route id to detect you are the sitemap and skip the `validatePreviewToken` there

Note that if you want to prerender the **entire** site, you will not be able to use the pagination as it is currently implemented with ``/posts?pageIndex=123` but will have to implement some routing mechanism such that you get `/posts/123`

**Comment by stephane-vanraes** [comment]
I will have a look at updating the project to sveltekit 2.0 during the holidays and perhaps write a guide for SSG as well :)

**Comment by psntr** [comment]
As always thanks for the prompt reply and solution. By adding the bool `building`, it worked. 

Additionally I'm wondering if I made a mistake, but for instance, if you edit an already **published** Post, and want to have a preview of the recent changes that is not "published" but only saved, it seems that it's not showing the unpublished recent changes on an already published Post.

**Comment by stephane-vanraes** [comment]
Ah that's because you get both the draft and the published version in the returned array
Have a look at the two latest commits 

https://github.com/stephane-vanraes/sveltekit-sanity-starter/commit/a3518907946f2ae138fdad140a5afcb9516f3131
https://github.com/stephane-vanraes/sveltekit-sanity-starter/commit/d1dae47aa13af464fae36fd6a299338cd14a760e

Those two take into consideration changes by filtering out from the list items that have a draft of themselves (keeping only the draft in preview mode) and by using the last one in the actual page, not 100% sure of both but it should work fine

**Comment by GalleryCOMMON** [comment]
Thank you I could implement the one for getting all the posts, however I'm not sure about the logic on the one for the `posts/[slug]` since you aren't using the `.drafts` to check if the content is published or not. Do you mind explaining the reason you do the `const post = locals.isPreviewMode ? posts[posts.length - 1] : posts[0];`?

**Comment by psntr** [comment]
Thank you I could implement it for the posts index, but one the single post one I'm struggling to understand how it works to get the unpublished content since you are not using the `_id` to check if it has `draft` in it but you do:
`const post = locals.isPreviewMode ? posts[posts.length - 1] : posts[0];` could you explain this please?

**Comment by stephane-vanraes** [comment]
Thanks for the comment, it made me rethink the approach here.
The idea was that since both versions come I would take either the last or the first one but this would assume they are correctly sorted chronologically. Going from there I decided to force the order, which in turn led me to just dump this code and pick the first one after sorting directly (you will not get the drafts without the preview token so it is fine)

see the code here https://github.com/stephane-vanraes/sveltekit-sanity-starter/commit/dde0baa06bb7654191c825da79e666234add0b40

**Comment by psntr** [comment]
Ok I see, makes sense, thank you keep on updating the repo, I learned a lot! Closing the issue :)
